### ISSUE TITLE
Command+E

### ISSUE THREAD

**Issue by jokinL** [arshad/Sketch-Navigator#2]
I like your plugin but I use Zeplin and Zeplin use Command+E when you need export the artboards.
Can we change Command to other convination? :(

Thank for your work

**Comment by arshad** [comment]
Looking into it.

**Comment by arshad** [comment]
As far as I can tell, Sketch does not let plugins customize keyboard shortcuts. It has to be hardcoded inside the manifest file. Luckily, it's easy to change.

1. Go to your plugins directory, right click on the **Sketch-Navigator.sketchplugin** and click on **Show Package Contents**.
2. Find the manifest.json file inside Contents/Sketch.
3. Edit the manifest.json file and update the **shortcut** value under commands.

**Comment by jokinL** [comment]
I found it yesterday night but I haven't got time to answer you sorry.
Thank so much!
